# Generated by Django 2.1.1 on 2019-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.URLField(verbose_name='Фото')),
                ('price', models.CharField(max_length=30, verbose_name='Стоимость')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
    ]
